### ISSUE TITLE
Canary deployment not able to process Bigger OSM files

### ISSUE THREAD

**Issue by Junaid-Ahmed94** [peter-evans/nominatim-k8s#41]
I am trying to deploy nominatim for Europe, but even after 48 hours (approx.) it is still running and it is just Germany's OSM file.
For Maldives file (which is given in example) it works fine but as soon as I move to bigger files it seems to be taking just too much time. Below is my canary deployment file. (I am just pasting the spec.template.spec portion)
```
spec:
      volumes:
        - name: nominatim-secret-volume
          secret:
            secretName: osm-storage
      containers:
        - name: nominatim-k8s
          image: peterevans/nominatim-k8s:2.5.4
          env:
            - name: NOMINATIM_MODE
              value: CREATE
            - name: NOMINATIM_PBF_URL
              value: "https://download.geofabrik.de/europe/germany-latest.osm.pbf"
            - name: NOMINATIM_DATA_LABEL
              value: germany-2020
            - name: NOMINATIM_SA_KEY_PATH
              value: "/etc/nominatim-secret-volume/KeyFile.json"
            - name: NOMINATIM_PROJECT_ID
              value: my-project-id
            - name: NOMINATIM_GS_BUCKET
              value: "gs://my-bucket-path"
          volumeMounts:
            - name: nominatim-secret-volume
              readOnly: true
              mountPath: /etc/nominatim-secret-volume
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 26Gi
            requests:
              memory: 24Gi
          readinessProbe:
            httpGet:
              path: /search
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
```
Maldives file is just 3.1 MB but Germany file is 3.2 GB. Does it need more resources for 3.2GB file size then I have already restricted it too ?
